apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnkmysql
  labels:
    app: bnkmysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bnkmysql
  template:
    metadata:
      labels:
        app: bnkmysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.services.mysql.image.repository }}:{{ .Values.services.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.services.mysql.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.mysql.service.port }}
          env:
            - name: MYSQL_DATABASE
              value: "{{ .Values.db.name }}"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
