apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miage-bank.fullname" . }}-configserver
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      serviceAccountName: {{ include "miage-bank.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: configserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          # On va chercher l'image spécifique au config server :
          image: "{{ .Values.services.configServer.image.repository }}:{{ .Values.services.configServer.image.tag }}"
          imagePullPolicy: {{ .Values.services.configServer.image.pullPolicy }}
          env:
            - name: WAIT_HOSTS
              value: "bnkannuaire:{{ .Values.services.annuaire.service.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.configServer.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.services.configServer.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.services.configServer.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # (IMPORTANT) On ajoute le volume /tmp dont on avait parlé :
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}