apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnkcompteservice
  labels:
    app: bnkcompteservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bnkcompteservice
  template:
    metadata:
      labels:
        app: bnkcompteservice
    spec:
      containers:
        - name: compteservice
          image: "{{ .Values.services.compteService.image.repository }}:{{ .Values.services.compteService.image.tag }}"
          imagePullPolicy: {{ .Values.services.compteService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.compteService.service.port }}
          env:
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: WAIT_HOSTS
              value: "bnkconfigsrv:{{ .Values.services.configServer.service.port }}, bnkmongo:{{ .Values.services.mongo.service.port }}"
          args:
            - "--spring.data.mongodb.username="
            - "--spring.data.mongodb.password="
            - "--spring.data.mongodb.host="
            - "--spring.data.mongodb.port="
