{{- range $name, $config := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miage-bank.fullname" $ }}-{{ $name }}
  labels:
    app: {{ $name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      serviceAccountName: {{ include "miage-bank.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
          imagePullPolicy: {{ $config.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $config.port }}
              protocol: TCP
          
          # Si le service a des variables d'environnement définies, on les injecte :
          {{- if $config.env }}
          env:
            {{- toYaml $config.env | nindent 12 }}
          {{- end }}
          
          # Le fameux volume temporaire obligatoire pour Spring Boot
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
{{- end }}