apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnkmongo
  labels:
    app: bnkmongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bnkmongo
  template:
    metadata:
      labels:
        app: bnkmongo
    spec:
      serviceAccountName: {{ include "miage-bank.serviceAccountName" . }}
      containers:
        - name: mongo
          image: "{{ .Values.services.mongo.image.repository }}:{{ .Values.services.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.services.mongo.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.mongo.service.port }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.services.mongo.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.services.mongo.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.secretName }}
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.secretName }}
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongo.database | quote }}
