apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnkapigateway
  labels:
    app: bnkapigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bnkapigateway
  template:
    metadata:
      labels:
        app: bnkapigateway
    spec:
      serviceAccountName: {{ include "miage-bank.serviceAccountName" . }}
      containers:
        - name: apigateway
          image: "{{ .Values.services.apiGateway.image.repository }}:{{ .Values.services.apiGateway.image.tag }}"
          imagePullPolicy: {{ .Values.services.apiGateway.image.pullPolicy }}
          ports:
            - containerPort: 10050
          livenessProbe:
            tcpSocket:
              port: 10050
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 10050
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://bnkconfigsrv:10003"
            - name: SERVER_PORT
              value: "10050"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: WAIT_HOSTS
              value: 'bnkconfigsrv:{{ .Values.services.configServer.service.port }}, bnkmongo:{{ .Values.services.mongo.service.port }}, bnkcompteservice:{{ .Values.services.compteService.service.port }}, bnkclientservice:{{ .Values.service.port }}, bnkcompositeservice:{{ .Values.services.compositeService.service.port }}'
