apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "miage-bank.fullname" . }}-db-secret
  labels:
    {{- include "miage-bank.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ include "miage-bank.fullname" . }}-vault
    kind: SecretStore
  target:
    name: {{ .Values.db.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.vault.secretPath }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.vault.secretPath }}
        property: password
