apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnkmysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:oracle
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "banquebd"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secretName }}
              key: username
              optional: true
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secretName }}
              key: password
              optional: true
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bnkmysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
