apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "miage-bank.fullname" . }}-vault
  labels:
    {{- include "miage-bank.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.kvPath }}
      version: {{ .Values.vault.version }}
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.tokenSecretName }}
          key: token
