apiVersion: v1
kind: Service
metadata:
  name: bnkcompteservice
  labels:
    app: bnkcompteservice
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.compteService.service.port }}
      targetPort: {{ .Values.services.compteService.service.port }}
      protocol: TCP
      name: http
  selector:
    app: bnkcompteservice
