{{- range $name, $config := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  # Le nom du service sera la clé du yaml (ex: bnkconfigsrv ou client-service)
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $config.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $name }}
{{- end }}