apiVersion: v1
kind: Service
metadata:
  name: bnkclientservice
  labels:
    app: bnkclientservice
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.services.clientService.service.port }}
      targetPort: {{ .Values.services.clientService.service.port }}
      protocol: TCP
      name: http
  selector:
    app: bnkclientservice
