apiVersion: v1
kind: Service
metadata:
  name: bnkmysql
  labels:
    app: bnkmysql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.mysql.service.port }}
      targetPort: {{ .Values.services.mysql.service.port }}
      protocol: TCP
      name: mysql
  selector:
    app: bnkmysql
