apiVersion: v1
kind: Service
metadata:
  name: bnkmongo
  labels:
    app: bnkmongo
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.mongo.service.port }}
      targetPort: {{ .Values.services.mongo.service.port }}
      protocol: TCP
      name: mongo
  selector:
    app: bnkmongo
