apiVersion: v1
kind: Service
metadata:
  name: bnkcompositeservice
  labels:
    app: bnkcompositeservice
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.compositeService.service.port }}
      targetPort: {{ .Values.services.compositeService.service.port }}
      protocol: TCP
      name: http
  selector:
    app: bnkcompositeservice
