replicaCount: 1

services:
  # Annuaire
  bnkannuaire:
    image:
      repository: ghcr.io/edenkha/miage-bank-annuaire
      tag: "latest"
      pullPolicy: Always
    port: 10001

  # Config Server
  bnkconfigsrv:
    image:
      repository: ghcr.io/edenkha/miage-bank-configserver
      tag: "latest"
      pullPolicy: Always
    port: 10003

  # API Gateway
  bnkapigateway:
    image:
      repository: ghcr.io/edenkha/miage-bank-gateway
      tag: "latest"
      pullPolicy: Always
    port: 10000

  # Client Service
  bnkclientservice:
    image:
      repository: ghcr.io/edenkha/miage-bank-client
      tag: "latest"
      pullPolicy: Always
    port: 10011
    env:
      - name: MYSQL_HOST
        value: "bnkmysql.default.svc.cluster.local"
      - name: MYSQL_DATABASE
        value: "banquebd"

  # Compte Service
  bnkclientservice:
    image:
      repository: ghcr.io/edenkha/miage-bank-compte
      tag: "latest"
      pullPolicy: Always
    port: 10021
    env:
      - name: SPRING_DATA_MONGODB_HOST
        value: "bnkmongo.default.svc.cluster.local"
      - name: SPRING_DATA_MONGODB_PORT
        value: "27017"
      - name: SPRING_DATA_MONGODB_DATABASE
        value: "banquebd"

  # Client Compte (Composite)
  bnkclientcompte:
    image:
      repository: ghcr.io/edenkha/miage-bank-composite
      tag: "latest"
      pullPolicy: Always
    port: 10031
